- hosts: all
  gather_facts: no
  pre_tasks:
  - setup:
  roles:
  - base
  tags: base

- hosts: unbound
  gather_facts: no
  roles:
  - unbound
  tags: unbound

- hosts: letsencrypt
  gather_facts: no
  roles:
  - letsencrypt
  tags: letsencrypt

- hosts: email
  gather_facts: no
  roles:
  - email
  tags: email

- hosts: journalwatch
  gather_facts: no
  roles:
  - journalwatch
  tags: journalwatch

- hosts: bind
  gather_facts: no
  roles:
  - bind
  tags: bind

- hosts: etherpad
  gather_facts: no
  roles:
  - etherpad
  tags: etherpad

- hosts: prosody
  gather_facts: no
  roles:
  - prosody
  tags: prosody

- hosts: apache
  gather_facts: no
  roles:
  - apache
  tags: apache
