- hosts: all
  roles:
  - base
  tags: base

- import_playbook: upgrade.yml

- hosts: letsencrypt
  roles:
  - letsencrypt
  tags: letsencrypt

- import_playbook: email.yml

- hosts: bind
  roles:
  - bind
  tags: bind

- hosts: prosody
  roles:
  - prosody
  tags: prosody

- hosts: apache
  roles:
  - apache
  tags: apache
