# base
- name: create dh2048 file
  command: openssl dhparam -out {{ postfix.paths.dh2048 }} 2048
  args:
    creates: "{{ postfix.paths.dh2048 }}"
# daemons
- import_tasks: unbound.yml
  tags: unbound
- import_tasks: opendkim.yml
  tags: opendkim
  when: postfix.opendkim is defined
- import_tasks: postfix.yml
  tags: postfix
