- name: install postfix
  apt: name=postfix,bsd-mailx state=latest
- name: install postfix config
  register: config_main
  template:
    src: templates/{{ item }}
    dest: /etc/postfix/{{ item }}
  with_items:
  - main.cf
  - master.cf
- name: reload postfix
  service: name=postfix state=restarted enabled=yes
  when: config_main.changed
- name: delete old local-mail cronjob
  file: path=/etc/cron.daily/local-mail state=absent
- name: install check-for-local-mail cronjob
  copy:
    src: files/check-for-local-mail
    dest: /etc/cron.daily/check-for-local-mail
    mode: u=rwx,g=rx,o=rx
