#!/bin/bash
set -e

# Fix for some providers messing with DNS settings
if ! diff /etc/resolv.conf /etc/resolv.conf.unbound > /dev/null; then
	echo "Someone messed up our DNS! Fixing it..."
	cp /etc/resolv.conf.unbound /etc/resolv.conf
{% if 'email' in group_names %}
	# Just to make sure postfix uses the new settings
	systemctl restart postfix
{% endif %}
fi
