postfix:
  # postmaster email address
  postmaster: postmaster@example.org
  # optional: Whether to put a postscreen on port 25
  postscreen: True
  # optional: Open another SMTP daemon on port 26 that only accepts mail from local hosts
  # (and whitelisted client certs, if applicable).  Useful when the source of the mail is in
  # a network that blocks port 25 outgoing.
  smtpd_26: True
  # optional: Whether to accept emails for arbitrary destination on the submission port,
  # authenticated by dovecot.  Requires a dovecot: section (see below).
  submission: True
  # optional: From which IPs to accept mail.
  mynetworks: '127.0.0.0/8 [::1]/128 203.0.113.0/24'
  # optional: Hostnames and SHA1 certificate hashes that are allowed to relay email via this host.
  relay_client_cert_whitelist:
    - hostname: other.example.org
      cert: 00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33
  # optional: Configure a host to relay all outgoing email to.
  # Incompatible with smtp_outgoing.
  relay_host: mx.example.org
  # optional: Files in /etc/postfix ($FILE.crt, $FILE.key) to use as client certificates when
  # relaying to the relay_host.
  relay_client_cert: client_cert
  # optional: List multiple outgoing transports using different IP addresses.
  # Requires default_smtp_outgoing to be set to one of them.  The file
  # /etc/postfix/sender_transport_map on the server can be used to configure
  # which transport is used depending on the sender address.
  smtp_outgoing:
    - name: smtp1
      hostname: one.example.org
      ip: 203.0.113.1
      ip_v6: 2001:DB8::1
    - name: smtp2
      hostname: two.example.org
      ip: 203.0.113.2
  default_smtp_outgoing: smtp1
  # optional: Enabled opendkim for incoming and outgoing DKIM support.
  opendkim:
    # list of private keys
    private_keys:
    - example.org
    # table mapping outgoing domains to the private key used for signing mail
    signing_table:
      example.org: example.org
      lists.example.org: example.org
  # optional: install and configure mailman
  mailman:
    default_host: lists.example.org
    default_lang: en # if you change this, also run "dpkg-reconfigure mailman" to enable more languages
    domains: # the file /etc/postfix/virtual_alias_map can be used to configure aliases
    - lists.example.org
    default_footer: "-- \n%(list_name)s@%(host_name)s - %(description)s\nConfiguration: %(web_page_url)slistinfo%(cgiext)s/%(list_name)s\nUnsubscribe: %(list_name)s-unsubscribe@%(host_name)s\n"
    form_secret: $RANDOM
  # optional: Install and configure dovecot
  dovecot:
    domains: # the file /etc/postfix/virtual_alias_map can be used to configure aliases
    - example.org
    mysql_password: $RANDOM
    vmail_uid: 200
    mail_gid: 8
    quota:
      general: 1G
      trash: +10M
    # Hostname used for both web access (to changepw) and SMTP/IMAP servers in emails
    # sent by newmail script.
    host: mail.example.org
    # optional: Where to generate a CGI script that users can use to change their password
    changepw_cgi: /srv/mail.example.org/cgi/changepw

apache:
  default_host: www.example.org
  webmaster: webmaster@example.org
  server_name: web.example.org

prosody:
  host: jabber.example.org
  admins:
  - admin@jabber.example.org

bind:
  # which IPv4 address to listen on
  listen: 203.0.113.1
  # optional: which IPv4 address to listen on
  listen_v6: 2001:DB8::1

etherpad:
  domain: pad.example.org
  default_text: "Welcome to Etherpad!\\n\\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\\n\\nGet involved with Etherpad at http:\/\/etherpad.org\\n"
  mysql_password: $RANDOM
  admin_password: $RANDOM
